version: '3.8'
services:
  nginx-proxy:
    image: nginx:stable-alpine
    container_name: local-nginx-proxy
    restart: always
    ports:
      - '8081:8081' # expose on localhost:8081
      # add more ports if you need multiple listeners
    volumes:
      - ./proxies:/etc/nginx/conf.d:ro
    extra_hosts:
      - 'host.docker.internal:host-gateway'
